server:
  port: 9000
spring:
  security:
    management:
      enabled: false
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 1234
    jpa:
      show-sql: true
      properties:
        hibernate:
          ddl-auto: create
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true

management:
  security:
    enabled: false


logging:
  file:
    name: /Oasis/User-Microservice/Logging/${spring.application.name}/logs
