server:
  port: 9000
spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 1234
    jpa:
      show-sql: true
      properties:
        hibernate:
          ddl-auto: create
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: /Oasis/User-Microservice/Logging/${spring.application.name}/logs
